name: 'Build Android APK'
description: 'Builds an Android APK'
inputs:
  build_type:
    description: 'The type of build (e.g., debug, release)'
    required: true
    default: 'release'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build APK
      run: ./gradlew assemble${{ inputs.build_type }}
