name: 'Build Android APK'
description: 'Builds an Android APK'
runs:
  using: 'composite'
  shell: 'bash'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build APK
      run: ./gradlew assembleDebug
